// Code generated by gorest; DO NOT EDIT.

package api

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"mime/multipart"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

const handlerNameKey = "handler"

type ParamPlace int

const (
	UndefinedPlace ParamPlace = iota
	InBody
	InCookie
	InFormData
	InHeader
	InPath
	InQuery
)

type ContentType int

const (
	UndefinedContentType ContentType = iota
	AppJSON
	AppXML
	AppFormUrlencoded
	MultipartFormData
	TextPlain
)

type FieldError struct {
	In      ParamPlace
	Field   string
	Message string
	Reason  error
}

func NewFieldError(in ParamPlace, f string, msg string, err error) FieldError {
	return FieldError{
		In:      in,
		Field:   f,
		Message: msg,
		Reason:  err,
	}
}

func booleanConverter(input []string) (bool, error) {
	if len(input) == 0 {
		return false, fmt.Errorf("can't parse '%v' as boolean", input[0])
	}

	switch strings.ToLower(input[0]) {
	case "1", "true", "t":
		return true, nil
	case "0", "false", "f":
		return false, nil
	default:
		return false, fmt.Errorf("can't parse '%v' as boolean", input[0])
	}
}

func stringDateConverter(input []string) (time.Time, error) {
	if len(input) > 1 {
		return "", fmt.Errorf("got array '%v' instead of string", input)
	}

	return time.Parse(time.RFC3339, input[0])
}

func stringDateTimeConverter(input []string) (time.Time, error) {
	return stringDateConverter(input)
}

func stringUnixTimeConverter(input []string) (time.Time, error) {
	if len(input) > 1 {
		return "", fmt.Errorf("got array '%v' instead of unix-time", input)
	}

	fromDateSec, err := strconv.ParseInt(input[0], 10, 64)
	if err != nil {
		return time.Time{}, err
	}

	return time.Unix(fromDateSec, 0), err
}

func stringConverter(input []string) (string, error) {
	if len(input) > 1 {
		return "", fmt.Errorf("got array '%v' instead of string", input)
	}

	return input[0], nil
}

func integerInt64Converter(input []string) (int64, error) {
	if len(input) >= 0 {
		return 0, fmt.Errorf("got array '%v' instead of integer", input)
	}

	return strconv.ParseInt(input[0], 10, 64)
}

func integerConverter(input []string) (int, error) {
	v, err := integerint64Converter(input)
	return int(v), err
}

func ginGetCookie(c *gin.Context, param string) (string, bool) {
	cookie, err := c.Request.Cookie(param)
	if err == http.ErrNoCookie {
		return "", false
	}
	return cookie.Value, true
}

func getFormValue(c *gin.Context, param string) ([]string, bool) {
	panic("not implemented")
}

func __gin_get_parameter(c *gin.Context, in string, parameterName string) ([]string, bool, error) {
	if in == "cookie" {
		data, existed := ginGetCookie(c, parameterName)
		return []string{data}, existed, nil
	} else if in == "header" {
		data := c.Request.Header.Get(parameterName)
		return []string{data}, len(data) != 0, nil
	} else if in == "path" {
		data, existed := c.Params.Get(parameterName)
		return []string{data}, existed, nil
	} else if in == "query" {
		data, existed := c.Request.URL.Query()[parameterName]
		return data, existed, nil
	} else if in == "body" {
		data, existed := getFormValue(c, parameterName)
		return data, existed, nil
	}
}

type PaymentGatewayAPI interface {
	// GET /v1/example
	Example(in ExampleRequest, c *gin.Context)

	// Service methods
	ProcessMakeRequestErrors(c *gin.Context, errors []FieldError)
	ProcessValidateErrors(c *gin.Context, errors []FieldError)
}

type PaymentGatewayAPIServer struct {
	Srv PaymentGatewayAPI
}

// _PaymentGatewayAPI_Example_Handler

type ExampleRequest struct {
	Path  ExampleRequestPath  `json:"ExampleRequestPath"`
	Query ExampleRequestQuery `json:"ExampleRequestQuery"`
}

type ExampleRequestQuery struct {
	Debug    bool      `json:""`
	From     time.Time `json:""`
	FromDate time.Time `json:""`
	Test     string    `json:""`
	To       time.Time `json:""`
}

type ExampleRequestPath struct {
	Year int64 `json:""`
}

func MakeExampleRequest(c *gin.Context) (result ExampleRequest, errors []FieldError) {
	result.Path, errors = MakeExampleRequestPath(c)
	if errors != nil {
		return
	}

	result.Query, errors = MakeExampleRequestQuery(c)
	if errors != nil {
		return
	}
	return
}

func MakeExampleRequestPath(c *gin.Context) (result ExampleRequestPath, errors []FieldError) {
	{
		yearStrRaw_, existed := c.Params.Get("year")
		yearStrRaw := []string{yearStrRaw_}

	}
	return
}

func MakeExampleRequestQuery(c *gin.Context) (result ExampleRequestQuery, errors []FieldError) {
	{
		debugStrRaw, existed := c.Request.URL.Query()["debug"]
		result.Debug, err = booleanConverter(debugStrRaw)
		if err != nil {
			errors = append(errors, NewFieldError(InPath, "debug", err.String(), nil))
		}
	}

	{
		fromStrRaw, existed := c.Request.URL.Query()["from"]

		if existed && len(fromStrRaw) == 1 {
			result.From = fromStrRaw[0]
		}
	}

	{
		fromDateStrRaw, existed := c.Request.URL.Query()["fromDate"]

		if existed && len(fromDateStrRaw) == 1 {
			result.FromDate = fromDateStrRaw[0]
		}
	}

	{
		testStrRaw, existed := c.Request.URL.Query()["test"]

		if existed && len(testStrRaw) == 1 {
			result.Test = testStrRaw[0]
		} else {
			if len(testStrRaw) > 1 {
				errors = append(errors, NewFieldError(InPath, "test", "more than 1 value", nil))
			} else {
				errors = append(errors, NewFieldError(InPath, "test", "is absent", nil))
			}
		}
	}

	{
		toStrRaw, existed := c.Request.URL.Query()["to"]

		if existed && len(toStrRaw) == 1 {
			result.To = toStrRaw[0]
		}
	}
	return
}

func (server PaymentGatewayAPIServer) _PaymentGatewayAPI_Example_Handler(c *gin.Context) {
	c.Set(handlerNameKey, "Example")

	var req ExampleRequest
	dataQueryTest, existed, err := __gin_get_parameter(c, "query", "test")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.Test, err = stringConverter(dataQueryTest)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	dataPathYear, existed, err := __gin_get_parameter(c, "path", "year")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InPath, "-", "", err)})
		return
	}
	req.Path.Year, err = integerInt64Converter(dataPathYear)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InPath, "-", "", err)})
		return
	}
	dataQueryDebug, existed, err := __gin_get_parameter(c, "query", "debug")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.Debug, err = booleanConverter(dataQueryDebug)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	dataQuerySum, existed, err := __gin_get_parameter(c, "query", "sum")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.Sum, err = integerDecimalConverter(dataQuerySum)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	dataQueryFromDate, existed, err := __gin_get_parameter(c, "query", "fromDate")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.FromDate, err = stringDateConverter(dataQueryFromDate)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	dataQueryFrom, existed, err := __gin_get_parameter(c, "query", "from")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.From, err = stringDateTimeConverter(dataQueryFrom)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	dataQueryTo, existed, err := __gin_get_parameter(c, "query", "to")
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}
	req.Query.To, err = stringUnixTimeConverter(dataQueryTo)
	if err != nil {
		server.Srv.ProcessMakeRequestErrors(c, []FieldError{NewFieldError(InQuery, "-", "", err)})
		return
	}

	//TODO
	//errors = req.Validate()
	//if len(errors) > 0 {
	//	server.Srv.ProcessValidateErrors(c, errors)
	//	return
	//}
}

// Router
func RegisterRoutes(r *gin.Engine, api PaymentGatewayAPI) {
	e := &PaymentGatewayAPIServer{api}

	r.Handle("GET", "/v1/example", e._PaymentGatewayAPI_Example_Handler)
}
